json.id user.id
json.first_name  user.f_name
json.last_name  user.l_name
json.email user.email
json.address user.address
json.city user.city
json.state user.state
json.zip user.zip
json.phone user.phone